env:
  GO111MODULE: "on"

matrix:
  include:
  - language: python
    install:
    - pip install codespell
    script:
    - codespell --skip="vendor,*.git,*.png,*.pdf,*.tiff,*.plist,*.pem,rangesim*.go,*.gz"

  - language: go
    go:
    - "1.12.x"
    - master
    before_install:
    - go get github.com/mattn/goveralls
    script:
    - make style test build
    - $GOPATH/bin/goveralls  -coverprofile=.coverprofile -service=travis-ci
