apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "trickster.fullname" . }}
  labels:
    app: {{ template "trickster.name" . }}
    chart: {{ template "trickster.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  trickster.conf: |-
    [main]
    # instance_id allows you to run multiple trickster processes on the same host and log to separate files
    # Useful for baremetal, not so much for elastic deployments, so only uncomment if you really need it
    #instance_id = 1

    # Configuration options for the Proxy Server
    [proxy_server]
    # listen_port defines the port on which Trickster's Proxy server listens.
    # The default proxy is for Prometheus, so we use 9090 by default, just like Prometheus does
    # listen_port = 9090
    listen_port = {{ .Values.service.port }}
    # listen_address defines the ip on which Trickster's Proxy server listens.
    # empty by default, listening on all interfaces
    # listen_address =


    [caches]

        # [caches.default]
        # cache_type defines what kind of cache Trickster uses
        # options are 'bbolt', 'filesystem', 'memory', and 'redis'.
        # The default is 'memory'.
        # type = 'memory'

        # record_ttl_secs defines the relative expiration of cached timeseries. default is 6 hours (21600 seconds)
        # record_ttl_secs = 21600

        # reap_interval_ms defines how long the cache reaper waits between reap cycles. Default is 1000 (1s)
        # reap_interval_ms = 1000

        # compression determines whether the cache should be compressed. default is true
        # changing the compression setting will leave orphans in your cache for the duration of record_ttl_secs
        # compression = true

            ### Configuration options when using a Redis Cache
            # [cache.redis]
            # protocol defines the protocol for connecting to redis ('unix' or 'tcp') 'tcp' is default
            # protocol = 'tcp'
            # endpoint defines the fqdn+port or path to a unix socket file for connecting to redis
            # default is 'redis:6379'
            # endpoint = 'redis:6379'
            # password provides the redis password
            # default is empty
            # password = ''

            ### Configuration options when using a Filesystem Cache
            # [cache.filesystem]
            # cache_path defines the directory location under which the Trickster cache will be maintained
            # default is '/tmp/trickster'
            # cache_path = '/tmp/trickster'

            # Configuration options when using a bbolt Cache
            #[cache.bbolt]

            # filename defines the file where the Trickster cache will be maintained
            # default is 'trickster.db'
            # filename = 'trickster.db'

            # bucket defines the name of the BotlDb bucket (similar to a namespace) under which our key value store lives
            # default is 'trickster'
            # bucket = 'trickster'

      {{- range .Values.caches }}
        {{ printf "[caches.%s]" .name }}
        type = {{ .type | quote }}
        record_ttl_secs = {{ .recordTTLSecs | default(21600) }}
        {{ if .reapIntervalMs }}
        reap_interval_ms = {{ .reapIntervalMs }}
        {{ end }}
        compression = {{ .compression }}

            {{- if eq .type "redis" }}
            [cache.redis]
            protocol = {{ .redis.protocol | quote }}
            endpoint = {{ .redis.endpoint | quote }}
            password = {{ .redis.password | quote }}

            {{- else if eq .type "filesystem" }}
            [cache.filesystem]
            cache_path = {{ .filesystem.path | quote }}

            {{- else if eq .type "bbolt" }}
            [cache.bbolt]
            filename = {{ .bbolt.file | quote }}
            bucket = {{ .boltdb.bucket | quote }}
            {{- end }}
      {{- end }}


    # Configuration options for mapping Origin(s)
    [origins]

        ### The default origin
        # [origins.default]

        # type identifies the origin type. Valid options are 'prometheus', 'influxdb'
        # default is prometheus.
        # type = 'prometheus'

        # cache_name identifies the name of the cache (configured above) that you want to use with this origin proxy.
        # cache_name = 'default'

        # scheme identifies the scheme
        # default is http
        # scheme = 'http'

        # host identifies the upstream origin by fqdn/IP and port
        # default is prometheus:9090
        # host = 'prometheus:9090'

        # path_prefix provides any path that is prefixed onto the front of the client's requested path
        # default is empty
        # path_prefix = ''

        # timeout_secs defines how many seconds Trickster will wait before aborting and upstream http request. Default: 180s
        # timeout_secs = 180

        # api_path defines the path of the Upstream Origin's API (usually '/api/v1')
        # api_path = '/api/v1'

        # ignore_no_cache_header disables a client's ability to send a no-cache to refresh a cached query. Default is false
        # ignore_no_cache_header = false

        # max_value_age_secs defines the maximum age of data in the cached timeseries. Default is 86400 (24 hours)
        # max_value_age_secs = 86400

        # fast_forward_disable, when set to true, will turn off the 'fast forward' feature for any requests proxied to this origin
        # fast_forward_disable = false

    {{- range .Values.origins }}
        {{ printf "[origins.%s]" .name }}
        type = {{ .type | quote }}
        cache_name = {{ .name }}
        scheme = {{ .scheme | quote }}
        host = {{ .host | quote }}
        path_prefix = {{ .pathPrefix | quote }}
        api_path = {{ .apiPath | quote }}
        ignore_no_cache_header = {{ .ignoreNoCacheHeader }}
        max_value_age_secs = {{ .maxValueAgeSecs }}
        timeout_secs = {{ .timeoutSecs }}
        backfill_tolerance_secs = {{ .backfillToleranceSecs }}
        fast_forward_disable = {{ .fastForwardDisable }}
    {{- end }}

        # [origins.foo]
        # type = 'influxdb'
        # cache_name = default
        # scheme = 'http'
        # host = 'influx-origin:8086'
        # path_prefix = ''
        # api_path = ''
        # ignore_no_cache_header = false
        # max_value_age_secs = 86400
        # timeout_secs = 180
        # backfill_tolerance_secs = 180
        # fast_forward_disable = false

    # Configuration Options for Metrics Instrumentation
    [metrics]
    # listen_port defines the port that Trickster's metrics server listens on at /metrics
    listen_port =  {{ .Values.service.metricsPort }}
    # listen_address defines the ip that Trickster's metrics server listens on at /metrics
    # empty by default, listening on all interfaces
    # listen_address =

    # Configruation Options for Profiler
    [profiler]
    # enabled indicates whether to start the profiler server when Trickster starts up. Default: false
    # enabled = false
    enabled = {{ .Values.profiler.enabled }}
    # listen_port defines the port that Trickster's profiler server listens on at /debug/pprof. Default: 6060
    # listen_port = 6060
    listen_port = {{ .Values.profiler.port }}

    # Configuration Options for Logging Instrumentation
    [logging]
    # log_level defines the verbosity of the logger. Possible values are 'debug', 'info', 'warn', 'error'
    # default is info
    log_level = {{ .Values.logLevel | quote }}

    # log_file defines the file location to store logs. These will be auto-rolled and maintained for you.
    # not specifying a log_file (this is the default behavior) will print logs to STDOUT
    # log_file = '/some/path/to/trickster.log'
