apiVersion: v1
kind: Service
metadata:
  {{- if .Values.prometheusScrape }}
  annotations:
    prometheus.io/scrape: {{ .Values.prometheusScrape | quote }}
    prometheus.io/port: {{ .Values.service.metricsPort | quote }}
    prometheus.io/path: /metrics
  {{- end }}
  name: {{ template "trickster.fullname" . }}
  labels:
    app: {{ template "trickster.name" . }}
    chart: {{ template "trickster.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
{{- if not (empty .Values.service.nodePort) }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
{{- if not (empty .Values.service.metricsNodePort) }}
      nodePort: {{ .Values.service.metricsNodePort }}
{{- end }}
  selector:
    app: {{ template "trickster.name" . }}
    release: {{ .Release.Name }}
